# Generated by Django 2.2.2 on 2019-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psqlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
